sonar.projectKey=estefano-nascimento_study-sync
sonar.organization=estefano-nascimento

sonar.sources=.
sonar.exclusions=node_modules/**,android/**,ios/**,dist/**,build/**,.expo/**,coverage/**,__tests__/**,__mocks__/**

sonar.coverage.exclusions=app/**,coverage/**,generate-assets.js,babel.config.js,metro.config.js,jest.config.js,assets/**,__tests__/**,__mocks__/**

sonar.javascript.lcov.reportPaths=coverage/lcov.info
