sonar.projectKey=estefano-nascimento_study-sync
sonar.organization=estefano-nascimento

sonar.sources=.
sonar.exclusions=node_modules/**,android/**,ios/**,dist/**,build/**,.expo/**

sonar.javascript.lcov.reportPaths=coverage/lcov.info
